#!/usr/bin/env bash
set -euo pipefail

CONF_DIR="/etc/ssh/sshd_config.d"
CONF_FILE="${CONF_DIR}/99_custom_sshd.conf"


if [[ $EUID -ne 0 ]]; then
  echo "ERROR: Please run as root (e.g., sudo $0)" >&2
  exit 1
fi

# sshd setting

PORT="$1"
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || (( PORT < 1 || PORT > 65535 )); then
  echo "Error: invalid port: $PORT" >&2
  exit 1
fi

mkdir -p "${CONF_DIR}"

cat > "${CONF_FILE}" <<EOF
# Created by $(basename "$0")
Port ${PORT}
PasswordAuthentication yes
PermitRootLogin prohibit-password

ClientAliveInterval 300
ClientAliveCountMax 2

MaxStartups 10:30:60
AllowGroups sshusers
EOF

chmod 644 "${CONF_FILE}"
sshd -t

# Make new user (you)
read -r -p "Your username: " USER
if [[ -z "${USER}" ]]; then
  echo "Error: username is empty." >&2
  exit 1
fi

if id "$USER" &>/dev/null; then
  echo "Error: user already exist: ${USER}" >&2
  exit 1
fi

useradd -m -s /bin/bash "$USER"
passwd "$USER"

groupadd -f sshusers
usermod -aG sshusers,sudo "$USER"

HOME_DIR="$(getent passwd "$USER" | cut -d: -f6)"
SRC_DIR="$(pwd)"

rsync -av --chown="$USER:$USER" "$SRC_DIR" "${HOME_DIR}/"

# Enable Firewall
ufw allow 22/tcp
ufw allow "$PORT"/tcp
ufw --force enable

# Reload ssh
systemctl stop ssh.socket || true
systemctl disable ssh.socket || true
systemctl restart ssh

# fail2ban install
apt install -y fail2ban
systemctl enable --now fail2ban

cat > /etc/fail2ban/jail.local <<EOF
# This file is auto-generated by $(basename "$0")

[DEFAULT]
banaction = ufw

[sshd]
enabled = true
port = ${PORT}
backend = systemd
maxretry = 5
findtime = 10m
bantime = 24h
EOF

systemctl restart fail2ban
ss -plnt | grep sshd
# Guideline
cat <<EOF


==============================================
[NEXT STEPS]
1) From a NEW terminal, verify SSH login using the new port:
   ssh -p ${PORT} ${USER}@<SERVER_IP_OR_HOST>

2) After login, confirm that files/scripts were copied correctly:
   ls -al /home/${USER}/$(basename "$(pwd)")

3) If everything looks good, remove the old user (CAUTION):
   sudo killall -u <OLD_USER>
   sudo deluser --remove-home <OLD_USER>

4) Finally, exit the current SSH session:
   exit
==============================================
EOF


