#!/usr/bin/env python3
import argparse
import ipaddress
import subprocess
import sys
from pathlib import Path

DEFAULT_DNS = ["147.46.80.1","147.46.37.10","8.8.8.8","1.1.1.1"]


def detect_nic() -> str:
    command = r"""ip -br link | awk '$2=="UP" && $0 ~ /LOWER_UP/ && $1 ~ /^(enp|ens|eno|eth)/ {print $1; exit}'"""
    nic = subprocess.check_output(command, shell=True, text=True).strip()
    if not nic:
        print("No suitable NIC found.", file=sys.stderr)
        sys.exit(2)
    return nic



def main():
    p = argparse.ArgumentParser(description="Generate netplan YAML from IPv4 CIDR. GW/DNS are preset.")
    p.add_argument("--addr", required=True, help="IPv4 addr, e.g. 192.168.0.10")
    p.add_argument("--nic", help="NIC name (optional). If omitted, auto-detect via `ip -br link`.")
    p.add_argument("--out")
    args = p.parse_args()

    try:
        ipv4_addr = ipaddress.ip_address(args.addr)
    except ValueError:
        print(f"ERROR: bad --addr: {args.addr}", file=sys.stderr)
        sys.exit(2)
    if ipv4_addr.version != 4:
        print("ERROR: only IPv4 addr is supported.", file=sys.stderr)
        sys.exit(2)

    nic = args.nic or detect_nic()
    if not nic.startswith(('enp', 'ens', 'eno', 'eth')):
        print(f"ERROR: bad NIC: {nic}", file=sys.stderr)
        sys.exit(2)

    print(f"[OK] addr={ipv4_addr} NIC={nic}")

    gateway = ipaddress.IPv4Address((int(ipv4_addr) & 0xFFFFFF00) | 1)

    dns = ", ".join(DEFAULT_DNS)
    text = f"""# Generated by {Path(__file__).name}
network:
  version: 2
  ethernets:
    {nic}:
      dhcp4: no
      addresses: [{ipv4_addr}/24]
      routes:
        - to: default
          via: {gateway}
      nameservers:
        addresses: [{dns}]
"""

    out = Path(args.out)
    out.write_text(text, encoding="utf-8")
    print(f"{out} written\n")


if __name__ == "__main__":
    main()
