#!/usr/bin/env bash

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: Please run as root (e.g., sudo $0)" >&2
  exit 1
fi


if ! command -v figlet >/dev/null 2>&1; then
    apt install -y figlet
fi

MOTD_DIR="/etc/update-motd.d"

TARGET_FILES=(
    "50-landscape-sysinfo"
    "90-updates-available"
    "85-fwupd"
    "92-unattended-upgrades"
    "98-reboot-required"
    "98-fsck-at-reboot"
    "95-hwe-eol"
)

read -r -p "Enter server name: " SERVER_NAME

cat > "${MOTD_DIR}/01-custom-header" <<EOF
#!/usr/bin/env bash

# This file is auto-generated by $(basename "$0")

figlet " ${SERVER_NAME}"
EOF


cat > "${MOTD_DIR}/51-hardware-sysinfo" << EOF
#!/usr/bin/env bash

# This file is auto-generated by $(basename "$0")
set -euo pipefail

# CPU (force English output)
cpu_model="\$(LC_ALL=C lscpu | awk -F: '/Model name/ {sub(/^[ \t]+/, "", \$2); print \$2; exit}')"
cpu_sockets="\$(LC_ALL=C lscpu | awk -F: '/Socket\\(s\\)/ {sub(/^[ \t]+/, "", \$2); print \$2; exit}')"
cpu_cores="\$(LC_ALL=C lscpu | awk -F: '/Core\\(s\\) per socket/ {sub(/^[ \t]+/, "", \$2); print \$2; exit}')"
cpu_threads="\$(LC_ALL=C lscpu | awk -F: '/^CPU\\(s\\)/ {sub(/^[ \t]+/, "", \$2); print \$2; exit}')"

# Memory
mem_total="\$(free -h | awk '/^Mem:/ {print \$2}')"

echo ""
echo "  Hardware Specs"
printf "  CPU : %s\n" "\${cpu_model:-Unknown}"
printf "    Sockets: %s | Cores/socket: %s | Threads: %s\n" "\${cpu_sockets:-?}" "\${cpu_cores:-?}" "\${cpu_threads:-?}"
printf "  MEM : %s\n" "\${mem_total:-Unknown}"
printf ""
EOF


cat > "${MOTD_DIR}/52-gpu-sysinfo" <<EOF
#!/usr/bin/env bash

# This file is auto-generated by $(basename "$0")

if ! command -v nvidia-smi &> /dev/null; then
    exit 0
fi

echo ""
echo -e "  GPU Status"

PROC_COUNT=\$(nvidia-smi --query-compute-apps=pid --format=csv,noheader | wc -l)

nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits | \
awk -v procs="\$PROC_COUNT" -F', ' '{
    mem_pct = (\$4 / \$5) * 100

    printf "  GPU [%d] %-18s: %3s%% Util | %5s / %5s MiB (%.1f%%)\n", \$1, \$2, \$3, \$4, \$5, mem_pct
}'

echo "  Active GPU Processes: \$PROC_COUNT"
echo ""

EOF


TARGET_FILES+=("01-custom-header" "51-hardware-sysinfo" "52-gpu-sysinfo")

find "$MOTD_DIR" -maxdepth 1 -type f -exec chmod a-x {} +


for file in "${TARGET_FILES[@]}"; do
    FILE_PATH="$MOTD_DIR/$file"

    if [ -f "$FILE_PATH" ]; then
        chmod 755 "$FILE_PATH"
    fi
done


# Static motd disabled
sudo sed -i -E '/^[[:space:]]*#/! s/^([[:space:]]*session[[:space:]]+optional[[:space:]]+pam_motd\.so[[:space:]]+noupdate)/#\1/' /etc/pam.d/sshd
